// <auto-generated/>
namespace AbpInsight.Resources
{
  using System;
  using JetBrains.Application.I18n;
  using JetBrains.DataFlow;
  using JetBrains.Diagnostics;
  using JetBrains.Lifetimes;
  using JetBrains.Util;
  using JetBrains.Util.Logging;
  using JetBrains.Application.I18n.Plurals;
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  public static class Strings
  {
    private static readonly ILogger ourLog = Logger.GetLogger("AbpInsight.Resources.Strings");

    static Strings()
    {
      CultureContextComponent.Instance.Change.Advise(Lifetime.Eternal, args =>
      {
          var instance = args.HasNew ? args.New : null;
          if (instance != null)
          {
            ourResourceManager = new Lazy<JetResourceManager>(
              () =>
              {
                return instance
                  .CreateResourceManager("AbpInsight.Resources.Strings", typeof(Strings).Assembly);
              });
          }
          else
          {
            ourResourceManager = null;
          };
      });
    }
    
    private static Lazy<JetResourceManager> ourResourceManager = null;
    
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static JetResourceManager ResourceManager
    {
      get
      {
        var resourceManager = ourResourceManager;
        if (resourceManager == null)
        {
          return ErrorJetResourceManager.Instance;
        }
        return resourceManager.Value;
      }
    }

    public static string Choice(string format, params object[] args)
    {
        var formatter = ResourceManager.ChoiceFormatter;
        if (formatter == null) return "???";
        return string.Format(formatter, format, args);
    }

    public static string IncorrectModuleNamingWarning_Message => ResourceManager.GetString("IncorrectModuleNamingWarning_Message");
    public static string ModuleContainsParameterizedConstructor_Message => ResourceManager.GetString("ModuleContainsParameterizedConstructor_Message");
    public static string ModuleTypeMustBePublic_Message => ResourceManager.GetString("ModuleTypeMustBePublic_Message");
    public static string DependencyTypeMustBePublic_Message => ResourceManager.GetString("DependencyTypeMustBePublic_Message");
    public static string DependencyImplementsMultipleLifetimes_Message => ResourceManager.GetString("DependencyImplementsMultipleLifetimes_Message");
    public static string DependsOnNonAbpModuleType_Message => ResourceManager.GetString("DependsOnNonAbpModuleType_Message");
  }
}